---
locale: pt-BR
subs:
  include_path: sub/*:plugins/*
  at:
    plugins/additionals:
      test:
        commands: []
    plugins/deprecated:
      test:
        commands: []
    plugins/redmine_git_hosting:
      test:
        commands: []
