AllCops:
  Exclude:
    - 'app/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'CONTRIBUTING.md'
    - 'db/**/*'
    - 'doc/**/*'
    - 'extra/**/*'
    - 'files/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'install/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'nbproject/**/*'
    - 'plugins/redmine_bootstrap_kit/**/*'
    - 'plugins/redmine_git_hosting/**/*'
    - 'public/**/*'
    - 'Rakefile'
    - 'README.rdoc'
    - 'script/**/*'
    - 'test/**/*'
    - 'tmp/**/*'

Rails:
  Enabled: true
  
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false
  
Metrics/AbcSize:
  Exclude:
    - 'plugins/*/db/migrate/**/*'
    - 'plugins/*/test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'plugins/*/test/**/*'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'plugins/*/db/migrate/**/*'    

Metrics/MethodLength:
  Exclude:
    - 'plugins/*/db/migrate/**/*'
    - 'plugins/*/test/**/*'
