--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
gitolite_user: ${gitolite_user}
gitolite_ssh_private_key: ${redmine_git_hosting_ssh_key_name}
gitolite_ssh_public_key: ${redmine_git_hosting_ssh_key_name}.pub
gitolite_server_port: '22'
gitolite_global_storage_dir: repositories/
gitolite_recycle_bin_dir: recycle_bin/
gitolite_redmine_storage_dir: ''
gitolite_temp_dir: /tmp/redmine_git_hosting_${gitolite_user}/
gitolite_script_dir: /tmp/redmine_git_hosting_scripts_${gitolite_user}/
gitolite_config_file: gitolite.conf
gitolite_config_has_admin_key: 'true'
gitolite_recycle_bin_expiration_time: '24.0'
gitolite_log_level: info
gitolite_log_split: 'false'
ssh_server_domain: ${server_address}
http_server_domain: ${server_address}
https_server_domain: ''
http_server_subdir: ''
show_repositories_url: 'true'
gitolite_daemon_by_default: '1'
gitolite_http_by_default: '1'
gitolite_hooks_are_asynchronous: 'false'
gitolite_force_hooks_update: 'true'
gitolite_hooks_debug: 'true'
gitolite_cache_max_time: '900'
gitolite_cache_max_size: '16'
gitolite_cache_max_elements: '2000'
gitolite_notify_by_default: '1'
gitolite_notify_global_prefix: ! '[REDMINE]'
gitolite_notify_global_sender_address: redmine@example.net
gitolite_notify_global_include: []
gitolite_notify_global_exclude: []
all_projects_use_git: 'false'
delete_git_repositories: 'false'
hierarchical_organisation: 'true'
unique_repo_identifier: 'true'

